version: "3.8"
services:
  # DeliveryTrackingApp:
  #   container_name: delivery-tracking-app
  #   image: ryanali12/delivery-tracking-app-dev
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./DeliveryTrackingApp:/app
  #   environment:
  #     KESTREL__ENDPOINTS__HTTP__URL: http://+:${APP_PORT}
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    ports:
      - "1433:1433"
    volumes:
      - ./database:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-02-26T09-33-48Z.fips
    volumes:
      - minio_storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
volumes:
  minio_storage: {}
