version: "3.8"
services:
  # DeliveryTrackingApp:
  #   container_name: delivery-tracking-app
  #   image: ryanali12/delivery-tracking-app-dev
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./DeliveryTrackingApp:/app
  #   environment:
  #     KESTREL__ENDPOINTS__HTTP__URL: http://+:${APP_PORT}
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
